version: '3.7'

services:
  protonvpn:
    build: .
    ports: ['1090:1080']
    privileged: true
    devices:
      - /dev/net/tun:/dev/net/tun
      - /etc/localtime:/etc/localtime
    cap_add:
      - NET_ADMIN
    environment:
      - PROTONVPN_USERNAME=MhDEyyypW76rpujJSCw63xGTqjk3WlBS
      - PROTONVPN_PASSWORD=Nuh2vpYKLqe0n8V9slq0EbXLfUpo5ysb
      - PROTONVPN_SERVER=CH-MX#1
