version: '3.7'

services:
  protonvpn:
    build: .
    ports: ['1090:1080']
    cap_add:
      - NET_ADMIN
    environment:
      - PROTONVPN_USERNAME=${PROTONVPN_USERNAME}
      - PROTONVPN_PASSWORD=${PROTONVPN_PASSWORD}
      - PROTONVPN_SERVER=CH-UK#1
