version: '3.7'

services:
  pvpn:
    build: .
    ports: ['1090:1080']
    cap_add:
      - NET_ADMIN
    environment:
      - PVPN_USERNAME=${PVPN_USERNAME}
      - PVPN_PASSWORD=${PVPN_PASSWORD}
      - PVPN_SERVER=CH-UK#1
